use crate::models::Error;
use std::path::Path;

/// Generates portable bash script for injecting references into agent context
pub fn generate_inject_script(
    _skill_path: &Path,
    reference_files: &[String],
) -> Result<String, Error> {
    if reference_files.is_empty() {
        return Ok(String::new());
    }

    let script = r#"#!/usr/bin/env bash
# Auto-generated by agentskills upgrade
# Injects references/ content into agent context before SKILL.md delivery
#
# This script uses progressive disclosure pattern with deduplication markers.
# Each reference file contains a marker comment that prevents duplicate injection.

set -euo pipefail

# Detect skill directory (parent of scripts/)
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Agent context file (set by agent runtime)
AGENT_CONTEXT="${AGENT_CONTEXT:-}"

if [ -z "$AGENT_CONTEXT" ]; then
  echo "Warning: AGENT_CONTEXT not set, skipping reference injection" >&2
  exit 0
fi

# Inject each reference file with deduplication check
for ref_file in "$SKILL_DIR"/references/*.md; do
  if [ ! -f "$ref_file" ]; then
    continue
  fi

  # Extract filename for marker
  ref_name="$(basename "$ref_file")"
  marker="<!-- injected: references/$ref_name -->"

  # Check if already injected
  if ! grep -q "$marker" "$AGENT_CONTEXT" 2>/dev/null; then
    cat "$ref_file" >> "$AGENT_CONTEXT"
  fi
done
"#;

    Ok(script.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_generate_inject_script_empty_references() {
        let result = generate_inject_script(&PathBuf::from("/tmp/skill"), &[]).unwrap();
        assert_eq!(result, "");
    }

    #[test]
    fn test_generate_inject_script_creates_valid_bash() {
        let refs = vec!["ref1.md".to_string(), "ref2.md".to_string()];
        let result = generate_inject_script(&PathBuf::from("/tmp/skill"), &refs).unwrap();

        // Should have shebang
        assert!(result.starts_with("#!/usr/bin/env bash"));

        // Should have dedup logic
        assert!(result.contains("<!-- injected: references/"));
        assert!(result.contains("grep -q \"$marker\""));

        // Should check AGENT_CONTEXT
        assert!(result.contains("AGENT_CONTEXT"));

        // Should iterate over references
        assert!(result.contains("for ref_file in"));
        assert!(result.contains("/references/*.md"));
    }

    #[test]
    fn test_generate_inject_script_handles_skill_dir() {
        let refs = vec!["ref1.md".to_string()];
        let result = generate_inject_script(&PathBuf::from("/tmp/skill"), &refs).unwrap();

        // Should detect SKILL_DIR relative to script location
        assert!(result.contains("SKILL_DIR="));
        assert!(result.contains("dirname"));
    }

    #[test]
    fn test_generate_inject_script_has_portable_bash() {
        let refs = vec!["ref1.md".to_string()];
        let result = generate_inject_script(&PathBuf::from("/tmp/skill"), &refs).unwrap();

        // Should use portable constructs (no bash 4+ arrays)
        assert!(!result.contains("declare -a"));
        assert!(!result.contains("readarray"));

        // Should use standard bash
        assert!(result.contains("set -euo pipefail"));
    }
}
